chambon2018:
  model: physioex.train.networks.chambon2018:Chambon2018Net
  preprocessing : raw
  target_transform: physioex.train.networks.utils.target_transform:get_mid_label

seqsleepnet:
  model: physioex.train.networks.seqsleepnet:SeqSleepNet
  preprocessing : xsleepnet
  target_transform: null
  model_kwargs:
    learning_rate : .0001

tinysleepnet:
  model: physioex.train.networks.tinysleepnet:TinySleepNet
  preprocessing : raw
  target_transform: null


seqsexnet:
  model: physioex.train.networks.seqsexnet:SeqSexNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    learning_rate : .000001
    weight_decay :  .0000001
    n_classes: 2

protosleepnet_reconstructor:
  model: physioex.train.networks.sample_reconstructor:SampleReconstructor
  preprocessing : xsleepnet,raw
  target_transform: null
  model_kwargs:
    proto_ck: /home/coder/shared/physioex/models/definitivi/mass_spectrograms/2lstm_drop_nobnrelu/proto/1sample/fold=-1-epoch=8-step=26066-val_loss=1.04.ckpt
    proto_model: protosleepnet_spectrogram
    section_length : 300
    proto_dim : 64
    N : 1
    n_prototypes : 50
    loss: physioex.train.networks.utils.loss:CrossEntropyLoss

    learning_rate : .0002

protosleepnet_spectrogram:
  model: physioex.train.networks.spectrogram:ProtoSleepNet
  preprocessing : xsleepnet
  target_transform: null
  model_kwargs:
    section_length : 300
    N : 1
    n_prototypes : 50
    loss: physioex.train.networks.utils.loss:CrossEntropyLoss

    learning_rate : .0001

default:
  model : null

  model_kwargs : 
    n_classes: 5
    sf : 100
    in_channels: null
    sequence_length : null
  
    loss: physioex.train.networks.utils.loss:CrossEntropyLoss
    loss_kwargs: {}

    learning_rate : .0001
    weight_decay :  .000001
  preprocessing : null
  target_transform : null


