chambon2018:
  model: physioex.train.networks.chambon2018:Chambon2018Net
  preprocessing : raw
  target_transform: physioex.train.networks.utils.target_transform:get_mid_label

seqsleepnet:
  model: physioex.train.networks.seqsleepnet:SeqSleepNet
  preprocessing : xsleepnet
  target_transform: null
  model_kwargs:
    learning_rate : .0001

tinysleepnet:
  model: physioex.train.networks.tinysleepnet:TinySleepNet
  preprocessing : raw
  target_transform: null


seqsexnet:
  model: physioex.train.networks.seqsexnet:SeqSexNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    learning_rate : .000001
    weight_decay :  .0000001
    n_classes: 2

protosleepnet:
  model: physioex.train.networks.prototype:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 5
    N : 1
    n_prototypes : 25

protosleepnet_n1p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 600
    N : 1
    n_prototypes : 25

protosleepnet_n3p125:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 5
    N : 3
    n_prototypes : 125

protosleepnet_p200n1p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 200
    N : 1
    n_prototypes : 25

protosleepnet_p200n2p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 200
    N : 2
    n_prototypes : 25

protosleepnet_p200n3p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 200
    N : 3
    n_prototypes : 25

protosleepnet_p200n4p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 200
    N : 4
    n_prototypes : 25

protosleepnet_p200n5p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 200
    N : 5
    n_prototypes : 25

protosleepnet_p300n1p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 300
    N : 1
    n_prototypes : 25

protosleepnet_p300n2p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 300
    N : 2
    n_prototypes : 25

protosleepnet_p300n3p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 300
    N : 3
    n_prototypes : 25

protosleepnet_p300n4p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 300
    N : 4
    n_prototypes : 25

protosleepnet_p300n5p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 300
    N : 5
    n_prototypes : 25

protosleepnet_p500n1p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 500
    N : 1
    n_prototypes : 25

protosleepnet_p500n2p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 500
    N : 2
    n_prototypes : 25

protosleepnet_p500n3p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 500
    N : 3
    n_prototypes : 25

protosleepnet_p500n4p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 500
    N : 4
    n_prototypes : 25

protosleepnet_p500n5p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 500
    N : 5
    n_prototypes : 25

protosleepnet_p600n1p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 600
    N : 1
    n_prototypes : 25

protosleepnet_p600n2p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 600
    N : 2
    n_prototypes : 25

protosleepnet_p600n3p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 600
    N : 3
    n_prototypes : 25

protosleepnet_p600n4p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 600
    N : 4
    n_prototypes : 25

protosleepnet_p600n5p25:
  model: physioex.train.networks.prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 600
    N : 5
    n_prototypes : 25

protosleepnet_reconstructor:
  model: physioex.train.networks.sample_reconstructor:SampleReconstructor
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_ck: /home/tinghi/models/hmc/temp/lr/fold=-1-epoch=10-step=15744-val_loss=inf.ckpt
    proto_model: "protosleepnet_n3p125"
    proto_lenght : 5
    N : 3
    n_prototypes : 125
    loss: physioex.train.networks.utils.loss:RegressionLoss

    learning_rate : .0002

protosleepnet_n7p25:
  model: physioex.train.networks.old_prototype_kl:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 600
    N : 7
    n_prototypes : 25

protosleepnet_reconstructor_mass:
  model: physioex.train.networks.sample_reconstructor:SampleReconstructor
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_ck: /home/coder/physioex/models/mass_diff_seqle/1ch/p200/n4/fold=-1-epoch=8-step=26630-val_loss=inf.ckpt
    proto_model: "protosleepnet_p200n4p25"
    proto_lenght : 200
    N : 4
    n_prototypes : 25
    loss: physioex.train.networks.utils.loss:RegressionLoss

    learning_rate : .0002

protosleepnet_p200n4p50_merged:
  model: physioex.train.networks.merged:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 200
    N : 4
    n_prototypes : 50
    loss: physioex.train.networks.utils.loss:CrossEntropyLoss

    learning_rate : .0001

protosleepnet_p300n4p50_merged:
  model: physioex.train.networks.merged:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 300
    N : 4
    n_prototypes : 50
    loss: physioex.train.networks.utils.loss:CrossEntropyLoss

    learning_rate : .0001

protosleepnet_p300n4p50_inverted:
  model: physioex.train.networks.inverted:ProtoSleepNet
  preprocessing : raw
  target_transform: null
  model_kwargs:
    proto_lenght : 300
    N : 4
    n_prototypes : 50
    loss: physioex.train.networks.utils.loss:CrossEntropyLoss

    learning_rate : .0001

protosleepnet_p300n4p50_spectrogram:
  model: physioex.train.networks.spectrogram:ProtoSleepNet
  preprocessing : xsleepnet
  target_transform: null
  model_kwargs:
    proto_lenght : 300
    N : 4
    n_prototypes : 50
    loss: physioex.train.networks.utils.loss:CrossEntropyLoss

    learning_rate : .0001

default:
  model : null

  model_kwargs : 
    n_classes: 5
    sf : 100
    in_channels: null
    sequence_length : null
  
    loss: physioex.train.networks.utils.loss:CrossEntropyLoss
    loss_kwargs: {}

    learning_rate : .0001
    weight_decay :  .000001
  preprocessing : null
  target_transform : null


